name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '19.6.0'

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test
