name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: "testing"
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        uses: stefanoeb/jest-action@1.0.3
        with:
          jestArgs: __tests__
